Parameters:
  #=======================================================
  #
  #                   CloudFormation Parameters
  #
  #=======================================================
  StackName:
    Type: String
    Default: ''
    Description: Unique identifier of the resources in this stack
  IdentifierToken:
    Type: String
    Default: ''
    Description: Unique identifier used for performing the 1nce Provision Callback.
  Codebase:
    Type: String
    Default: customer_stack.zip
    AllowedValues:
      - customer_stack.zip
    NoEcho: true
    Description: >-
      Zip file which contains the codebase needed for the deployment of the
      stack
  CodebaseBucket:
    Type: String
    Default: ''
    Description: Code base bucket name
  CodebaseVersion:
    Type: String
    Default: ''
    Description: Version of the CloudFormation Stack
  OverrideCallBackUrl:
    Type: String
    Default: ''
    Description: Parameter to override the Callback URL
  CallbackUrl:
    Type: String
    Default: ''
    Description: Parameter to override the Callback URL
  ApiKeyId:
    Type: String
    Default: ''
    Description: API key ID
  CertificatesUrl:
    Type: String
    Default: ''
    Description: Certificates URL
  MqttBridgeUrl:
    Type: String
    Default: ''
    Description: Mqtt Bridge URL
  CreateQueueSQSArn:
    Type: String
    Default: ''
    Description: Create SQS ARN
  CreateQueueSQSUrl:
    Type: String
    Default: ''
    Description: Create SQS URL
  1nceCrossAccountIamRoleArn:
    Type: String
    Default: ''
    Description: ARN of the cross-account IAM role used by 1nce to gain access to specific services
  IntegrationType:
    Type: String
    AllowedValues:
      - FULL_INTEGRATION
      - DATA_INTEGRATION
    Description: >-
      The integration type will determine if the customer uses a FULL_INTEGRATION solution
      including bridging and direct mqtt connectivity using things, certificates and policies. 
      Or if the customer just has a DATA_INTEGRATION and thus does only makes use of the bridging functionality.
  DeleteQueueSQSArn:
    Type: String
    Default: ''
    Description: Delete SQS ARN
  DeleteQueueSQSUrl:
    Type: String
    Default: ''
    Description: Delete SQS URL
  LambdaExecutionIamRoleArn:
    Type: String
    Default: ''
    Description: Lambda Execution IAM Role ARN
  StateMachineExecutionIamRoleArn:
    Type: String
    Default: ''
    Description: State Machine Execution IAM Role ARN
Resources:
  #=======================================================
  #
  #                     Log groups
  #
  #=======================================================
  CreateCallbackLambdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${StackName}-Create-CallbackLambda'
  CreateCallbackDownloadCodeLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${StackName}-Create-CallbackDownloadCodeLambda'
  #=======================================================
  #
  #                     S3 Buckets
  #
  #=======================================================
  CreateCallbackCodeBucketS3:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  #=======================================================
  #
  #                     Lambda IAM Role
  #
  #=======================================================
  CreateCallbackLambdaExecutionIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Join
            - '-'
            - - iot-core
              - lambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                Resource:
                  - !Sub >-
                    arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*
              - Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub >-
                    arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*:*
              - Effect: Allow
                Action:
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'apigateway:GET'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:DeleteObject'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                  - 's3:GetBucketPolicy'
                  - 'S3:PutObjectTagging'
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref CreateCallbackCodeBucketS3
                      - /*
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref CreateCallbackCodeBucketS3
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 'S3:GetObjectTagging'
                  - 's3:ListBucket'
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref CodebaseBucket
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref CodebaseBucket
                      - /
                      - !Ref CodebaseVersion
                      - /*
              - Effect: Allow
                Action:
                  - 'iot:describeEndpoint'
                Resource: '*'
      Path: /
  #=======================================================
  #
  #                     Lambda Functions
  #
  #=======================================================
  CreateCallbackDownloadCodeLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          import json
          import logging
          import threading
          import boto3
          import cfnresponse
          def copy_objects(source_bucket, dest_bucket, objects):
              s3 = boto3.client('s3')
              for o in objects:
                  copy_source = {
                      'Bucket': source_bucket,
                      'Key': o
                  }
                  print('copy_source: %s' % copy_source)
                  print('dest_bucket = %s'%dest_bucket)
                  s3.copy_object(CopySource=copy_source, Bucket=dest_bucket,
                        Key=o)
          def delete_objects(bucket, objects):
              s3 = boto3.client('s3')
              objects = {'Objects': [{'Key': o} for o in objects]}
              s3.delete_objects(Bucket=bucket, Delete=objects)
          def timeout(event, context):
              logging.error('Execution is about to time out, sending failure response to CloudFormation')
              cfnresponse.send(event, context, cfnresponse.FAILED, {}, None)
          def handler(event, context):
              # make sure we send a failure to CloudFormation if the function
              # is going to timeout
              timer = threading.Timer((context.get_remaining_time_in_millis()
                        / 1000.00) - 0.5, timeout, args=[event, context])
              timer.start()
              print('Received event: %s' % json.dumps(event))
              status = cfnresponse.SUCCESS
              try:
                  source_bucket = event['ResourceProperties']['SourceBucket']
                  dest_bucket = event['ResourceProperties']['DestBucket']
                  objects = event['ResourceProperties']['Objects']
                  if event['RequestType'] == 'Delete':
                      delete_objects(dest_bucket, objects)
                  else:
                      copy_objects(source_bucket, dest_bucket, objects)
              except Exception as e:
                  logging.error('Exception: %s' % e, exc_info=True)
                  status = cfnresponse.FAILED
              finally:
                  timer.cancel()
                  cfnresponse.send(event, context, status, {}, None)
      FunctionName: !Sub '${StackName}-Create-CallbackDownloadCodeService'
      Handler: index.handler
      MemorySize: 256
      Role: !GetAtt
        - CreateCallbackLambdaExecutionIamRole
        - Arn
      Runtime: python2.7
      Timeout: 240
      TracingConfig:
        Mode: Active
    DependsOn:
      - CreateCallbackDownloadCodeLogGroup
  CreateCallBackLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref CreateCallbackCodeBucketS3
        S3Key: !Join
          - ''
          - - !Ref CodebaseVersion
            - /
            - !Ref Codebase
      FunctionName: !Sub '${StackName}-CreateNotificationCallback'
      Handler: src/callback/create.callback
      MemorySize: 256
      Role: !GetAtt
        - CreateCallbackLambdaExecutionIamRole
        - Arn
      Runtime: nodejs12.x
      Timeout: 6
      TracingConfig:
        Mode: Active
    DependsOn:
      - CreateCallbackLambdaLogGroup
      - CreateCallbackCodeDownloadService
  #=======================================================
  #
  #                     Custom Services
  #
  #=======================================================
  CreateCallbackCodeDownloadService:
    Type: 'AWS::CloudFormation::CustomResource'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt 'CreateCallbackDownloadCodeLambdaFunction.Arn'
      DestBucket: !Ref 'CreateCallbackCodeBucketS3'
      SourceBucket: !Ref CodebaseBucket
      Objects:
        - !Join
          - ''
          - - !Ref CodebaseVersion
            - /
            - !Ref Codebase
  CreateNotificationService:
    Type: 'AWS::CloudFormation::CustomResource'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt
        - CreateCallBackLambdaFunction
        - Arn
      IdentifierToken: !Ref IdentifierToken
      CallbackUrl: !Ref CallbackUrl
      OverrideCallBackUrl: !Ref OverrideCallBackUrl
      AWS:
        AccountId: !Ref 'AWS::AccountId'
        Region: !Ref 'AWS::Region'
        LambdaExecutionIamRole: !Ref LambdaExecutionIamRoleArn
        StateMachineExecutionIamRole: !Ref StateMachineExecutionIamRoleArn
        CrossAccountIamRoleArn: !Ref 1nceCrossAccountIamRoleArn
      Resources:
        ApiKeyId: !Ref ApiKeyId
        Provisioning:
          Url: !Ref CreateQueueSQSUrl
          Arn: !Ref CreateQueueSQSArn
        Deprovisioning:
          Url: !Ref DeleteQueueSQSUrl
          Arn: !Ref DeleteQueueSQSArn
        Links:
          Certificates: !Ref CertificatesUrl
          Mqtt: !Ref MqttBridgeUrl
      1nce:
        IntegrationType: !Ref IntegrationType
      StackName: !Ref StackName
      CloudFormationVersion: !Ref CodebaseVersion
