Parameters:
  #=======================================================
  #
  #                   CloudFormation Parameters
  #
  #=======================================================
  IdentifierToken:
    Type: String
    Default: ''
    Description: Unique identifier used for performing the 1nce Provision Callback.
  Codebase:
    Type: String
    Default: customer_stack.zip
    AllowedValues:
      - customer_stack.zip
    NoEcho: true
    Description: >-
      Zip file which contains the codebase needed for the deployment of the
      stack
  IntegrationType:
    Type: String
    Default: 'FULL_INTEGRATION'
    AllowedValues:
      - FULL_INTEGRATION
#     TODO: uncomment after enabling DATA_INTEGRATION support
#      - DATA_INTEGRATION
    Description: >-
      The integration type will determine if the customer uses a FULL_INTEGRATION solution
      including sims and the connectivity suite.
#      TODO: uncomment after enabling DATA_INTEGRATION support
#      Or if the customer just has a DATA_INTEGRATION
#      and thus does not have 1nce sims but does use the connectivity suite.
  OverrideCallBackUrl:
    Type: String
    Default: ''
    Description: Parameter to override the Callback URL
  Environment:
    Type: String
    Default: Prod
    AllowedValues:
      - Prod
    Description: The environment used for the CloudFormation deployment
Mappings:
  #=======================================================
  #
  #                   CloudFormation Mappings
  #
  #=======================================================
  CallbackConfiguration:
    Prod:
      CallbackUrl: 'https://ymzgm41krk.execute-api.eu-central-1.amazonaws.com/prod/onboarding/customer'
  Configuration:
    Prod:
      1nceAWSId: '672401624271'
      CodebaseVersion: V1.0
      CodebaseBucket: prod-eu-central-1-cloudformation-templates
      PostbackCreateSnsArn: 'arn:aws:sns:eu-central-1:672401624271:prod-thing-provisioning-failed-topic'
      PostbackDeleteSnsArn: 'arn:aws:sns:eu-central-1:672401624271:prod-thing-deprovisioning-failed-topic'
      PostbackRegistrationQueueUrl: >-
        https://sqs.eu-central-1.amazonaws.com/672401624271/prod-provisioned-sims-sqs
      PostbackDeregistrationQueueUrl: >-
        https://sqs.eu-central-1.amazonaws.com/672401624271/prod-deprovisioned-sims-sqs
Conditions:
  #=======================================================
  #
  #                     Conditions
  #
  #=======================================================
  IntegrationTypeFilterFull: !Equals [ !Ref IntegrationType, FULL_INTEGRATION ]
  IntegrationTypeFilterData: !Equals [ !Ref IntegrationType, DATA_INTEGRATION ]
Resources:
  #=======================================================
  #
  #                   CloudFormation stacks
  #
  #=======================================================
  CustomerFullIntResourcesStack:
    Condition: IntegrationTypeFilterFull
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        StackName: !Ref AWS::StackName
        Codebase: !Ref Codebase
        1nceAWSId: !FindInMap
          - Configuration
          - !Ref Environment
          - 1nceAWSId
        CodebaseVersion: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseVersion
        CodebaseBucket: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseBucket
        PostbackCreateSnsArn: !FindInMap
          - Configuration
          - !Ref Environment
          - PostbackCreateSnsArn
        PostbackDeleteSnsArn: !FindInMap
          - Configuration
          - !Ref Environment
          - PostbackDeleteSnsArn
        PostbackRegistrationQueueUrl: !FindInMap
          - Configuration
          - !Ref Environment
          - PostbackRegistrationQueueUrl
        PostbackDeregistrationQueueUrl: !FindInMap
          - Configuration
          - !Ref Environment
          - PostbackDeregistrationQueueUrl
      TemplateURL: !Join
          - ''
          - - https://
            - !FindInMap
              - Configuration
              - !Ref Environment
              - CodebaseBucket
            - .s3-eu-central-1.amazonaws.com/
            - !FindInMap
              - Configuration
              - !Ref Environment
              - CodebaseVersion
            - /Customer-Stack-Full-Int-Resources.yaml
    DependsOn:
      - DeleteCallbackStack
  CustomerDataIntResourcesStack:
    Condition: IntegrationTypeFilterData
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        1nceAWSId: !FindInMap
          - Configuration
          - !Ref Environment
          - 1nceAWSId
      TemplateURL: !Join
          - ''
          - - https://
            - !FindInMap
              - Configuration
              - !Ref Environment
              - CodebaseBucket
            - .s3-eu-central-1.amazonaws.com/
            - !FindInMap
              - Configuration
              - !Ref Environment
              - CodebaseVersion
            - /Customer-Stack-Data-Int-Resources.yaml
    DependsOn:
      - DeleteCallbackStack
  CreateCallbackStackFull:
    Condition: IntegrationTypeFilterFull
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        StackName: !Ref AWS::StackName
        IdentifierToken: !Ref IdentifierToken
        Codebase: !Ref Codebase
        IntegrationType: !Ref IntegrationType
        ApiKeyId: !GetAtt CustomerFullIntResourcesStack.Outputs.ApiKeyId
        CertificatesUrl: !GetAtt CustomerFullIntResourcesStack.Outputs.CertificatesUrl
        CreateQueueSQSArn: !GetAtt CustomerFullIntResourcesStack.Outputs.CreateQueueSQSArn
        CreateQueueSQSUrl: !GetAtt CustomerFullIntResourcesStack.Outputs.CreateQueueSQSUrl
        DeleteQueueSQSArn: !GetAtt CustomerFullIntResourcesStack.Outputs.DeleteQueueSQSArn
        DeleteQueueSQSUrl: !GetAtt CustomerFullIntResourcesStack.Outputs.DeleteQueueSQSUrl
        1nceCrossAccountIamRoleArn: !GetAtt CustomerFullIntResourcesStack.Outputs.1nceCrossAccountIamRoleArn
        LambdaExecutionIamRoleArn: !GetAtt CustomerFullIntResourcesStack.Outputs.LambdaExecutionIamRole
        StateMachineExecutionIamRoleArn: !GetAtt CustomerFullIntResourcesStack.Outputs.StateMachineExecutionIamRole
        CodebaseBucket: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseBucket
        CodebaseVersion: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseVersion
        CallbackUrl: !FindInMap
          - CallbackConfiguration
          - !Ref Environment
          - CallbackUrl
        OverrideCallBackUrl: !Ref OverrideCallBackUrl
      TemplateURL: !Join
        - ''
        - - https://
          - !FindInMap
            - Configuration
            - !Ref Environment
            - CodebaseBucket
          - .s3-eu-central-1.amazonaws.com/
          - !FindInMap
            - Configuration
            - !Ref Environment
            - CodebaseVersion
          - /Customer-Stack-Create-Callback.yaml
  CreateCallbackStackData:
    Condition: IntegrationTypeFilterData
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        StackName: !Ref AWS::StackName
        IdentifierToken: !Ref IdentifierToken
        Codebase: !Ref Codebase
        IntegrationType: !Ref IntegrationType
        1nceCrossAccountIamRoleArn: !GetAtt CustomerDataIntResourcesStack.Outputs.1nceCrossAccountIamRoleArn
        CodebaseBucket: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseBucket
        CodebaseVersion: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseVersion
        CallbackUrl: !FindInMap
          - CallbackConfiguration
          - !Ref Environment
          - CallbackUrl
        OverrideCallBackUrl: !Ref OverrideCallBackUrl
      TemplateURL: !Join
        - ''
        - - https://
          - !FindInMap
            - Configuration
            - !Ref Environment
            - CodebaseBucket
          - .s3-eu-central-1.amazonaws.com/
          - !FindInMap
            - Configuration
            - !Ref Environment
            - CodebaseVersion
          - /Customer-Stack-Create-Callback.yaml
  DeleteCallbackStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        StackName: !Ref AWS::StackName
        IdentifierToken: !Ref IdentifierToken
        Codebase: !Ref Codebase
        OverrideCallBackUrl: !Ref OverrideCallBackUrl
        CodebaseBucket: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseBucket
        CodebaseVersion: !FindInMap
          - Configuration
          - !Ref Environment
          - CodebaseVersion
        CallbackUrl: !FindInMap
          - CallbackConfiguration
          - !Ref Environment
          - CallbackUrl
      TemplateURL: !Join
        - ''
        - - https://
          - !FindInMap
            - Configuration
            - !Ref Environment
            - CodebaseBucket
          - .s3-eu-central-1.amazonaws.com/
          - !FindInMap
            - Configuration
            - !Ref Environment
            - CodebaseVersion
          - /Customer-Stack-Delete-Callback.yaml
